import type {Category,Budget,Transaction} from './types';
export const categories:Category[]=[
 ['rent','Arriendo','Vivienda'],['admin','Administración','Vivienda'],['services','Servicios','Vivienda'],['internet','Internet','Vivienda'],['phone','Plan celular','Vivienda'],['food','Alimentación','Alimentación'],['market','Mercado','Alimentación'],['restaurants','Restaurantes','Alimentación'],['gas','Gasolina','Transporte'],['metro','Metro','Transporte'],['parking','Parqueaderos','Transporte'],['wash','Lavada','Transporte'],['vehicle','Mantenimiento vehículo','Transporte'],['outings','Salidas','Ocio'],['clothes','Ropa','Ocio'],['subscriptions','Suscripciones','Ocio'],['gym','Gimnasio','Salud'],['health','Salud','Salud'],['luna','Luna','Mascota'],['hair','Corte de pelo','Cuidado personal'],['other','Otros','Otros']
].map(([id,name,group])=>({id,name,group,type:'expense'}));
export const deductionCategories:Category[]=['Préstamo vehículo','Préstamo personal','FEC','Póliza','Salud','Pensión','Aporte voluntario','Retención en la fuente'].map((name,i)=>({id:`ded-${i}`,name,group:'Deducciones',type:'deduction'}));
export const savingCategories:Category[]=['Cuenta de ahorro','Fondo de emergencia','Inversiones','Ahorro viaje','Ahorro vehículo'].map((name,i)=>({id:`save-${i}`,name,group:'Patrimonio',type:'savings'}));
export const allCategories=[...categories,...deductionCategories,...savingCategories];
const limits:Record<string,number>={food:600000,rent:1875000,admin:150000,services:250000,internet:75000,phone:50000,subscriptions:73000,gas:250000,metro:100000,outings:400000,gym:250000,clothes:200000,luna:100000,parking:30000,wash:40000,hair:40000};
export const demoBudgets:Budget[]=Object.entries(limits).map(([categoryId,limit])=>({id:`b-${categoryId}`,month:'2026-09',categoryId,limit}));
const tx=(id:string,type:Transaction['type'],categoryId:string,amount:number,description:string,date='2026-09-05'):Transaction=>({id,type,categoryId,amount,description,date,account:'Cuenta principal',paymentMethod:type==='income'?'Nómina':'Débito',createdAt:date,updatedAt:date,demo:true});
export const demoTransactions:Transaction[]=[tx('1','income','save-0',6500000,'Salario','2026-09-01'),tx('2','deduction','ded-7',520000,'Retención en la fuente','2026-09-01'),tx('3','deduction','ded-5',260000,'Pensión','2026-09-01'),tx('4','expense','rent',1875000,'Arriendo','2026-09-01'),tx('5','expense','food',425000,'Mercado'),tx('6','expense','outings',285000,'Restaurantes y salidas'),tx('7','expense','gas',193000,'Gasolina'),tx('8','expense','subscriptions',73000,'Suscripciones'),tx('9','expense','gym',250000,'Gimnasio'),tx('10','savings','save-1',500000,'Fondo de emergencia'),tx('11','investment','save-2',300000,'Inversión mensual')];
